[theme]
primaryColor = "#6B8E23"  # Olive green for primary highlights
backgroundColor = "#FFF8DC"  # Cream for the background
secondaryBackgroundColor = "#F5DEB3"  # Lighter cream for secondary elements
textColor = "#556B2F"  # Olive green for text
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[runner]
magicEnabled = true
fastRerenderEnabled = true

[logger]
level = "info"
